---
abstract: 'Tapper - Wrapper for Benchmark::Perl::Formance'
author:
  - 'AMD OSRC Tapper Team, C<< <tapper at amd64.org> >>'
  - 'AMD OSRC Tapper Team <tapper@amd64.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: freebsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tapper-TestSuite-Benchmark-Perl-Formance
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Benchmark::Perl::Formance: 0.22
version: 3.000005
